/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.ServerSocket;
import java.net.Socket;

/**
 *
 * @author ESTUDIANTE
 */
public class ServidorVista extends javax.swing.JInternalFrame {

    /**
     * Creates new form ServidorVista
     */
    final int puerto = 5000;
    
    public ServidorVista() {
        initComponents();
    }
    
    public void iniciarServidor(){
    try {
        ServerSocket serverSocket = new ServerSocket(puerto);
        System.out.println("Servidor escuchando al puerto xdxd ");
        while (true) {                
            Socket clienteSocket = serverSocket.accept();
            System.out.println("Nuevo cliente conectado ");
            BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(clienteSocket.getInputStream()));
            //leer mensaje del cliente
            String mensaje = bufferedReader.readLine();
            System.out.println("Mensaje del cliente " + mensaje);
            bufferedReader.close();
            clienteSocket.close();
        }
    } catch (Exception e) {
        System.out.println("Pavlo aki ta fallando algo mmm " + e.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("HOLA PAVLO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(308, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
